# Default target
.PHONY: test help env-script

test:
	./tests/test-all.sh

env-script:
	@echo "Generating local setup script..."
	@echo '#!/bin/bash' > setup.sh
	@echo '' >> setup.sh
	@echo '# Auto-generated by make env-script' >> setup.sh
	@echo '# This file is local-only and gitignored' >> setup.sh
	@echo '' >> setup.sh
	@echo 'export AGENTIZE_HOME="$(CURDIR)"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/wt-cli.sh"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/lol-cli.sh"' >> setup.sh
	@chmod +x setup.sh
	@echo ""
	@echo "✓ Created setup.sh in repository root"
	@echo ""
	@echo "Usage:"
	@echo "  1. Source it now:  source setup.sh"
	@echo "  2. For persistence, add to your shell RC file:"
	@echo "     source $(CURDIR)/setup.sh"

help:
	@echo "Available targets:"
	@echo "  make test                - Run all tests"
	@echo "  make env-script          - Generate local setup.sh for development"
	@echo ""
	@echo "SDK usage:"
	@echo "  lol init --name your_project --lang c --path /path/to/project"
	@echo "  lol update                # From project directory"
	@echo "  lol --help                # For all options"