# Default target
.PHONY: test test-shells test-sdk test-cli test-lint test-e2e test-fast help setup pre-commit

test:
	./tests/test-all.sh

test-shells:
	TEST_SHELLS="bash zsh" ./tests/test-all.sh

test-sdk:
	./tests/test-all.sh sdk

test-cli:
	./tests/test-all.sh cli

test-lint:
	./tests/test-all.sh lint

test-e2e:
	./tests/test-all.sh e2e

test-fast:
	./tests/test-all.sh sdk cli lint

pre-commit:
	HOOKS_DIR=$$(git rev-parse --git-path hooks 2>/dev/null || echo ".git/hooks"); \
	mkdir -p "$$HOOKS_DIR"; \
	ln -sf ../../scripts/pre-commit "$$HOOKS_DIR/pre-commit"; \
	echo "✓ Pre-commit hook installed"; \

setup:
	@echo "Generating local setup script..."
	@echo '#!/bin/bash' > setup.sh
	@echo '' >> setup.sh
	@echo '# Auto-generated by make setup' >> setup.sh
	@echo '# This file is local-only and gitignored' >> setup.sh
	@echo '' >> setup.sh
	@echo 'export AGENTIZE_HOME="$(CURDIR)"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/wt-cli.sh"' >> setup.sh
	@echo 'source "$$AGENTIZE_HOME/scripts/lol-cli.sh"' >> setup.sh
	@echo '' >> setup.sh
	@echo '# Enable zsh completion for wt command' >> setup.sh
	@echo 'if [ -n "$$ZSH_VERSION" ]; then  # zsh-only setup' >> setup.sh
	@echo '  fpath=($$AGENTIZE_HOME/scripts/completions $$fpath)' >> setup.sh
	@echo '  # Re-initialize completion system to pick up new fpath' >> setup.sh
	@echo '  if command -v compdef >/dev/null 2>&1; then' >> setup.sh
	@echo '    # Already initialized, re-run to pick up new fpath' >> setup.sh
	@echo '    autoload -Uz compinit && compinit' >> setup.sh
	@echo '  else' >> setup.sh
	@echo '    # Not initialized yet, initialize now' >> setup.sh
	@echo '    autoload -Uz compinit && compinit' >> setup.sh
	@echo '  fi' >> setup.sh
	@echo 'fi' >> setup.sh
	@chmod +x setup.sh
	@echo ""
	@echo "✓ Created setup.sh in repository root"
	@echo ""
	@echo "Usage:"
	@echo "  1. Source it now:  source setup.sh"
	@echo "  2. For persistence, add to your shell RC file:"
	@echo "     cat setup.sh >> ~/.bashrc  # or ~/.zshrc"

help:
	@echo "Available targets:"
	@echo "  make test                - Run all tests (bash only)"
	@echo "  make test-shells         - Run all tests under multiple shells (bash and zsh)"
	@echo "  make test-sdk            - Run SDK template tests"
	@echo "  make test-cli            - Run CLI command tests"
	@echo "  make test-lint           - Run validation and linting tests"
	@echo "  make test-e2e            - Run end-to-end integration tests"
	@echo "  make test-fast           - Run fast tests (sdk + cli + lint)"
	@echo "  make setup               - Generate local setup.sh for development"
	@echo ""
	@echo "SDK usage:"
	@echo "  lol init --name your_project --lang c --path /path/to/project"
	@echo "  lol update                # From project directory"
	@echo "  lol --help                # For all options"
