name: Add issues and PRs to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

env:
  PROJECT_ORG: YOUR_ORG_HERE  # Replace with your GitHub organization
  PROJECT_ID: YOUR_PROJECT_ID_HERE  # Replace with your project number (e.g., 3)

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/${{ env.PROJECT_ORG }}/projects/${{ env.PROJECT_ID }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
